services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PORT
        value: 10000
